name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-${{ github.sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@master

    - name: Login to Docker Hub
      uses: docker/login-action@master
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build multi-platform images
      run: |
        docker buildx build --push --platform linux/amd64,linux/arm64 -t onepluskiller/tmp:${{ github.sha }} .

    - name: Set up Trivy and Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: onepluskiller/tmp:${{ github.sha }}
        format: 'json'
        output: 'trivy-results.json'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'

    - name: Fix vulnerabilities with COPA
      uses: project-copacetic/copa-action@main
      with:
        image: onepluskiller/tmp:${{ github.sha }}
        image-report: 'trivy-results.json'
        patched-tag: fixed
        output: fixed-image.tar

    - name: Load fixed image
      run: docker load -i fixed-image.tar

    - name: Push fixed image
      run: |
        docker tag onepluskiller/tmp:fixed onepluskiller/tmp:${{ github.sha }}
        docker push onepluskiller/tmp:${{ github.sha }}